### ISSUE TITLE
Erlang on AMI does not have dirty scheduler support

### ISSUE THREAD

**Issue by luckymike** [operable/cog#422]
I began playing with Cog this morning using the us-west-2 AMI. Initially things worked like a charm following the setup instructions. This afternoon, after toasting my initial machine, I built a new one and it does not have the correct Erlang, which seems pretty bonkers!

Brand new VM:
```

  Welcome to Cog Alpha!
  ---------------------

  This AMI is intended to provide a quickstart environment for
  exploring Cog with the necessary dependencies pre-installed. It
  is not intended for production use.

  If you have any problems, please feel free to ping us in chat,
  email, or in a GitHub issue at any time. Thanks so much for your
  help!

  A read-only SSH key with access to the Cog repositories has been
  installed for the operable user. In addition, Cog and the other
  related projects that are necessary for the alpha have been cloned
  into the /home/operable directory.

  We recommend using the /home/operable/cog.vars file to store any
  configuration customizations. Of particular note, you will need to edit
  the SLACK_API_TOKEN value that is in the file in order to connect
  to your Slack account. More information about how to get this token
  is available in the wiki.

  To get started, run the following commands:

  sudo su - operable
  ./setup.sh

admin@ip-10-0-0-124:~$ sudo su - operable
sudo: unable to resolve host ip-10-0-0-124
operable@ip-10-0-0-124:~$ ls
cog  cogctl  cog.vars  relay  relayctl  setup.sh
operable@ip-10-0-0-124:~$ ./setup.sh 
Loading environemnt variables from /home/operable/cog.vars.
Erlang installed...../usr/local/bin/erl
Elixir installed...../usr/local/bin/iex
Mix installed...../usr/local/bin/mix
Make installed...../usr/bin/make
Git installed...../usr/bin/git
Erlang dirty CPU schedulers supported.....No
Detected Erlang '/usr/local/bin/erl' lacks required dirty scheduler support.
See http://erlang.org/doc/installation_guide/INSTALL.html for more information.
Setup aborted.
```
Any idea what could be wrong? I'm open to operator error, though since I'm using a CFN template to provision, it's hard for me to imagine how I'd introduce any inconsistent actions.

**Comment by imbriaco** [comment]
@luckymike I suspect you do have dirty scheduler support, but that you are running on a single core VM. Erlang has to be coerced to enable SMP mode (and by extension, dirty schedulers) in that configuration.

Good news, though! We're announcing 0.3 tomorrow morning, but it's actually available right now. I just updated the wiki just few minutes ago with new AMIs that should solve your problem. One of the things that changes in 0.3.0 is the requirement for the enacl library which removes the need for us to require dirty scheduler support.

Let us know if that helps!

**Comment by imbriaco** [comment]
Drat, I'm mistaken about the current AMI. I'm building a new one right now that should fix this and I'll let you know when it's available. In the mean time, you can comment out the dirty scheduler check in setup.sh if you're using a current AMI from the wiki and it should work just fine.

**Comment by luckymike** [comment]
@imbriaco thanks for the quick reply. I immediately realized that I did change _one_ thing, the instance type. So that's almost surely it. I tried to checkout the 0.3.0 release, but I'm still getting the warning here, if that tag actually represents the dirty scheduler free release, you might have an issue in the Makefile. Will switch the instance type back up and hopefully be back to the 🏇

**Comment by luckymike** [comment]
Commenting out the check on 0.3.0 seems to have gotten me over the hurdle. Thanks again!

**Comment by imbriaco** [comment]
Oh, for goodness sake, we have it in the Makefile too. I completely forgot about that. We have that check sprinkled all over the place because it was a huge stumbling block for folks. Thanks for the heads up! I'm going to fix that and adjust the 0.3.0 tag accordingly. 

For the record, adjusting the tags like this is only happening because:

1. We haven't officially announced the release, and ...
2. We're in pretty early alpha still. 

Improving our release management process is very much on our short-term radar.

**Comment by luckymike** [comment]
I won't tell :)
